<?php
defined('ABSPATH') || exit;

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_623814598c9a1',
        'title' => 'Backlink',
        'fields' => array(
            array(
                'key' => 'field_62381467ae083',
                'label' => 'Aktifkan Backlink',
                'name' => 'aktifkan_backlink',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Tidak' => 'Tidak',
                    'Ya' => 'Ya',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'Tidak',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_62381484ae084',
                'label' => 'URL',
                'name' => 'url_backlink',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_62381467ae083',
                            'operator' => '==',
                            'value' => 'Ya',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_622eca576df29',
        'title' => 'Data Post Baru 2022',
        'fields' => array(
            array(
                'key' => 'field_622ecbd0f5551',
                'label' => 'Post Tipe Local Business',
                'name' => 'post_tipe_local_business',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'EmploymentAgency',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622ecab1d5cc0',
                'label' => 'alamat',
                'name' => 'alamat',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622eca9dd5cbd',
                'label' => 'local_custom',
                'name' => 'local_custom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622ecaa3d5cbe',
                'label' => 'local',
                'name' => 'local',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622ecaaad5cbf',
                'label' => 'provinsi',
                'name' => 'provinsi',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622ecd42d4ae5',
                'label' => 'kodepos',
                'name' => 'kodepos',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_622ed3e9e55f2',
                'label' => 'nama yang kasih review',
                'name' => 'nama_yang_kasih_review',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Handoko Setiawan',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 1,
                'show_column_sortable' => 1,
                'show_column_weight' => 1000,
                'allow_quickedit' => 1,
                'allow_bulkedit' => 1,
            ),
            array(
                'key' => 'field_623819cbaa098',
                'label' => 'Pakai No Telp Custom',
                'name' => 'pakai_no_telp_custom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_623819edaa099',
                'label' => 'No Telp Custom',
                'name' => 'no_telp_custom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_623819cbaa098',
                            'operator' => '==',
                            'value' => 'Ya',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_62381f3a675d4',
                'label' => 'Nama Perusahaan',
                'name' => 'nama_perusahaan_custom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_62382a222c025',
                'label' => 'Pakai Feed RSS?',
                'name' => 'pakai_feed_rss_custom',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Tidak' => 'Tidak',
                    'Ya' => 'Ya',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'Tidak',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_62382a452c026',
                'label' => 'Post Feed',
                'name' => 'post_feed_custom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_62382a222c025',
                            'operator' => '==',
                            'value' => 'Ya',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_6252858beb7d9',
                'label' => 'Pakai Custom Title',
                'name' => 'pakai_custom_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_625285aceb7da',
                'label' => 'Custom Title',
                'name' => 'custom_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_6252858beb7d9',
                            'operator' => '==',
                            'value' => 'Ya',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_622dde44a01ed',
        'title' => 'Profile Perusahaan CPT',
        'fields' => array(
            array(
                'key' => 'field_622ebb6fb4f75',
                'label' => 'Jenis Perusahaan',
                'name' => 'jenis_perusahaan',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Masukan dengan Kode Schema misal: Store, Employment Agency dst',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ddfcdfecc1',
                'label' => 'Jasa dan Layanan',
                'name' => 'jasa_dan_layanan_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622dde57fecb5',
                'label' => 'Nama Perusahaan',
                'name' => 'nama_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622dde67fecb6',
                'label' => 'Alamat Perusahaan',
                'name' => 'alamat_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622dde75fecb7',
                'label' => 'Kota',
                'name' => 'kota_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622dde88fecb8',
                'label' => 'Provinsi',
                'name' => 'provinsi_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622dde9afecb9',
                'label' => 'Nomor Telpon',
                'name' => 'nomor_telpon_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ddfb4fecc0',
                'label' => 'Kode Pos',
                'name' => 'kode_pos_perusahaan_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ddea6fecba',
                'label' => 'WA URL',
                'name' => 'wa_url_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ddeaefecbb',
                'label' => 'HP URL',
                'name' => 'hp_url_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622de33b9389a',
                'label' => 'Linkback',
                'name' => 'linkback_profile',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ddebdfecbc',
                'label' => 'Link',
                'name' => 'link_profile',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Row',
                'sub_fields' => array(
                    array(
                        'key' => 'field_622ddedbfecbd',
                        'label' => 'Nama Link',
                        'name' => 'nama_link_profile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'field_622ddebdfecbc',
                    ),
                    array(
                        'key' => 'field_622ddee8fecbe',
                        'label' => 'URL Link',
                        'name' => 'url_link_profile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'field_622ddebdfecbc',
                    ),
                    array(
                        'key' => 'field_622ddf1dfecbf',
                        'label' => 'Deskripsi Link',
                        'name' => 'deskripsi_link_profile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 75,
                        'parent_repeater' => 'field_622ddebdfecbc',
                    ),
                ),
                'rows_per_page' => 20,
            ),
            array(
                'key' => 'field_622dff19ae089',
                'label' => 'Pakai Feed',
                'name' => 'pakai_feed',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Tidak' => 'Tidak',
                    'Ya' => 'Ya',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'Tidak',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_622dff32ae08a',
                'label' => 'Feed URL',
                'name' => 'feed_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_622dff19ae089',
                            'operator' => '==',
                            'value' => 'Ya',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_622ec03cd40e3',
                'label' => 'Logo',
                'name' => 'logo_perusahaan_profile',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'profile-perusahaan',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;
